#FSR Autogenerated Content. DO NOT DELETE
from .get_arcanna_response import get_arcanna_response
from .send_feedback import send_feedback
from .get_jobs import get_jobs
from .send_to_arcanna import send_to_arcanna
 
supported_operations = {'get_arcanna_response': get_arcanna_response, 'send_feedback': send_feedback, 'get_jobs': get_jobs, 'send_to_arcanna': send_to_arcanna, }