LOGGER_NAME = 'arcanna'
EVENTS_ENDPOINT = '/api/v1/events/'
JOBS_ENDPOINT = '/api/v1/jobs'
EVENT_STATUS_FORMAT = '/api/v1/events/{}/{}'
EVENT_FEEDBACK_FORMAT = '/api/v1/events/{}/{}/feedback'
HEALTH_ENDPOINT = '/api/v1/health'
